In [2]:
import tensorflow as tf
from tensorflow import keras

In [3]:
class Linear(keras.layers.Layer):
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value = w_init(shape=(input_dim, units), dtype="float32"),
            trainable=True
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value = b_init(shape=(units, ), dtype="float32"), trainable=True
        )
    
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

In [4]:
x = tf.ones((2, 2))
linear_layer = Linear(4, 2)
y = linear_layer(x)
print(y)

tf.Tensor(
[[ 0.02378732  0.02853826 -0.11968675  0.05676496]
 [ 0.02378732  0.02853826 -0.11968675  0.05676496]], shape=(2, 4), dtype=float32)


In [5]:
assert linear_layer.weights == [linear_layer.w, linear_layer.b]

In [6]:
class Linear(keras.layers.Layer):
    def __init__(self, units=32, input_dim=32):
        super(Linear, self).__init__()
        self.w = self.add_weight(
            shape = (input_dim, units), initializer = "random_normal", trainable=True
        )
        self.b = self.add_weight(shape=(units, ), initializer="zeros", trainable=True)
    
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

x = tf.ones((2, 2,))
linear_layer = Linear(4, 2)
y = linear_layer(x)
print(y)

In [13]:
# 레이어는 훈련 불가능한 가중치를 가질 수 있다.
# assign_add : 기존의 값에서 인수값을 더함
# reduce_sum : axis 를 기준으로 값을 더함. 차원이 축소됨.
class ComputeSum(keras.layers.Layer):
    def __init__(self, input_dim):
        super(ComputeSum, self).__init__()
        self.total = tf.Variable(initial_value = tf.zeros((input_dim,)), trainable=False)
    
    def call(self, inputs):
        self.total.assign_add(tf.reduce_sum(inputs, axis=0))
        return self.total

x = tf.ones((2, 2))
my_sum = ComputeSum(2)
y = my_sum(x)
print(y.numpy())
y = my_sum(x)
print(y.numpy())

[2. 2.]
[4. 4.]


In [18]:
print("weights: ", len(my_sum.weights))
print("non-trainable weights:", len(my_sum.non_trainable_weights))

print("trainable_weights:", my_sum.trainable_weights)

weights:  1
non-trainable weights: 1
trainable_weights: []


In [ ]:
class Linear(keras.layers.Layer):
    def __init__(self, units=32):
        super(Linear, self).__init__()
        self.units = units
    
    def build(self, input_shape):
        self.w = self.add_weight(
            shape = (input_shape[-1], self.units),
            initializer = "random_normal",
            trainable=True,
        )
        self.b = self.add_weight(
            shape=(self.units,) , initializer="random_normal", trainable=True
        )
        
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

linear_layer = Linear(32)

y = linear_layer(x)

In [19]:
# 재귀적으로 구성 가능한 레이어

class MLPBlock(keras.layers.Layer):
    def __init__(self):
        super(MLPBlock, self).__init__()
        self.linear_1 = Linear(32)
        self.linear_2 = Linear(32)
        self.linear_3 = Linear(1)
    
    def call(self, inputs):
        x = self.linear_1(inputs)
        x = tf.nn.relu(x)
        x = self.linear_2(x)
        x = tf.nn.relu(x)
        return self.linear_3(x)

mlp = MLPBlock()
y = mlp(tf.ones(shape=(3, 64)))
print("weights:", len(mlp.weights))
print("trainable weight:", len(mlp.trainable_weights))

weights: 6
trainable weight: 6


In [20]:
# add_loss() 메서드
class ActivityRegularizationLayer(keras.layers.Layer):
    def __init__(self, rate=1e-2):
        super(ActivityRegularizationLayer, self).__init__()
        self.rate = rate
    
    def call(self, inputs):
        self.add_loss(self.rate * tf.reduce_sum(inputs))
        return inputs

In [21]:
class OuterLayer(keras.layers.Layer):
    def __init__(self):
        super(OuterLayer, self).__init__()
        self.activity_reg = ActivityRegularizationLayer(1e-2)
    
    def call(self, inputs):
        return self.activity_reg(inputs)

layer = OuterLayer()
assert len(layer.losses) == 0

_ = layer(tf.zeros(1, 1))
assert len(layer.losses) == 1

_ = layer(tf.zeros(1, 1))
assert len(layer.losses) == 1

In [23]:
# 가중치에 패널티를 주는 이유는 오버피팅을 막기 위해서. 
# kernel_regularizer : 각 층별 파라미터 or 출력값에 패널티를 부여. 그것에 대한 주요 효과는 오버피팅 방지. 

class OuterLayerWithKernelRegularizer(keras.layers.Layer):
    def __init__(self):
        super(OuterLayerWithKernelRegularizer, self).__init__()
        self.dense = keras.layers.Dense(
            32, kernel_regularizer=tf.keras.regularizers.l2(1e-3)
        )
    
    def call(self, inputs):
        return self.dense(inputs)

layer = OuterLayerWithKernelRegularizer()
_ = layer(tf.zeros((1, 1)))

print(layer.losses)

[<tf.Tensor: shape=(), dtype=float32, numpy=0.0020382036>]


In [24]:
# from_logits : 모델이 출력하는 output이 logit인지 아닌지를 판단하는 것. 
# from_logits=True이고 만일 2개의 분류라면, 결과값이 [0, 1] 이 아닌 [0.1, 0.9] 이런식으로 "확률" 로 나오게됨
"""
optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)
loss_fn = keras.losses.SparseCategoricalCrossentropy(from_logits=True)

for x_batch_train, y_batch_train in train_dataset:
    with tf.GradientTape()as tape:
        logits = layer(x_batch_train)
        loss_value = loss_fn(y_batch_train, logits)
        loss_value += sum(model.losses)
    
    grads = tape.gradient(loss_value, model.trainable_weights)
    optimizer.apply_gradients(zip(grads, model.trainable_weights))

"""

NameError: name 'train_dataset' is not defined

In [27]:
import numpy as np

inputs = keras.Input(shape=(3, ))
outputs = ActivityRegularizationLayer()(inputs)
model = keras.Model(inputs, outputs)

model.compile(optimizer="adam", loss="mse")
model.fit(np.random.random((2, 3)), np.random.random((2, 3)))

model.compile(optimizer="adam")
model.fit(np.random.random((2, 3)), np.random.random((2, 3)))

1/1 [==============================] - 0s 46ms/step - loss: 0.0199


In [30]:
# add_metric()
# 여기서 logits는 예측값(pred)을 의미. target은 label
class LogisticEndpoint(keras.layers.Layer):
    def __init__(self, name=None):
        super(LogisticEndpoint, self).__init__(name=name)
        self.loss_fn = keras.losses.BinaryCrossentropy(from_logits=True)
        self.accuracy_fn = keras.metrics.BinaryAccuracy()
    
    def call(self, targets, logits, sample_weights=None):
        loss = self.loss_fn(targets, logits, sample_weights)
        self.add_loss(loss)
        
        acc = self.accuracy_fn(targets, logits, sample_weights)
        self.add_metric(acc, name="accuracy")
        
        return tf.nn.softmax(logits)

In [36]:
layer = LogisticEndpoint()

targets = tf.ones((2, 2))
logits = tf.ones((2, 2))
y = layer(targets, logits)

print("layer.metrics:", layer.metrics)
print("current accuracy value:", float(layer.metrics[0].result()))

layer.metrics: [<tensorflow.python.keras.metrics.BinaryAccuracy object at 0x7ff8d9418820>]
current accuracy value: 1.0


In [42]:
inputs = keras.Input(shape=(3,), name="inputs")
targets = keras.Input(shape=(10,), name="targets")
logits = keras.layers.Dense(10)(inputs)
predictions = LogisticEndpoint(name="predictions")(logits, targets)

model = keras.Model(inputs=[inputs, targets], outputs=predictions)
model.compile(optimizer="adam")

data = {
    "inputs": np.random.random((3, 3)),
    "targets": np.random.random((3, 10)),
}
model.fit(data)

1/1 [==============================] - 0s 229ms/step - loss: 0.9191 - binary_accuracy: 0.0000e+00


In [43]:
# 레이어에서 선택적으로 직렬화를 활성화할 수 있다.
class Linear(keras.layers.Layer):
    def __init__(self, units=32):
        super(Linear, self).__init__()
        self.units = units
    
    def build(self, input_shape):
        self.w = self.add_weight(
            shape=(input_shape[-1], self.units),
            initializer="random_normal",
            trainable=True,
        )
        self.b = self.add_weight(
            shape=(self.units,), initializer="random_normal", trainable=True
        )
    
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    
    def get_config(self):
        return {"units": self.units}
    
layer = Linear(64)
config = layer.get_config()
print(config)
new_layer = Linear.from_config(config)

{'units': 64}


In [44]:
# 초기화시 부모 클래스에 **kwargs 전달하기
class Linear(keras.layers.Layer):
    def __init__(self, units=32, **kwargs):
        super(Linear, self).__init__(**kwargs)
        self.units = units
    
    def build(self, input_shape):
        self.w = self.add_weight(
            shape=(input_shape[-1], self.units),
            initializer="random_normal",
            trainable=True,
        )
        self.b = self.add_weight(
            shape=(self.units, ), initializer="random_normal", trainable=True
        )
    
    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b
    
    def get_config(self):
        config = super(Linear, self).get_config()
        config.update({"units": self.units})
        return config

    
layer = Linear(64)
config = layer.get_config()
print(config)
new_layer = Linear.from_config(config)

{'name': 'linear_6', 'trainable': True, 'dtype': 'float32', 'units': 64}


In [45]:
class CustomDropout(keras.layers.Layer):
    def __init__(self, rate, **kwargs):
        super(CustomDropout, self).__init__(**kwargs)
        self.rate = rate
    
    def call(self, inputs, training=None):
        if training:
            return tf.nn.dropout(inputs, rate=self.rate)
        return inputs

In [49]:
# layer : layer or block으로 불림
# model : model, network으로 불림.
# fit(), save() 등을 호출해야하는 경우라면 Model을 사용하고 그렇지 않은 경우라면 Layer를 사용하자. 

class ResNet(tf.keras.Model):
    
    def __init__(self):
        super(ResNet, self).__init__()
        self.block_1 = ResNetBlock()
        self.block_2 = ResNetBlock()
        self.global_pool = layers.GlobalAveragePooling2D()
        self.classifier = Dense(num_classes)
    
    def call(self, inputs):
        x = self.block_1(inputs)
        x = self.block_2(x)
        x = self.global_pool(x)
        return self.classifier(x)

resnet = ResNet()
dataset = ...
resnet.fit(dataset, epochs=10)
resnet.save(filepath)

NameError: name 'ResNetBlock' is not defined

지금까지 배운 것 정리
- Layer는 상태(__init__(), build()) 및 일부 계산(call())을 캡슐화한다.
- 레이어를 재귀적으로 중첩하여 새롭고 더 큰 계산 블록을 만들 수 있다.
- 레이어는 add_loss(), add_metric()을 통해 메트릭뿐만 아니라 손실을 생성 및 추적할 수 있다. 
- 훈련하려는 외부 컨테이너는 Model이다. Model은 Layer와 비슷하지만, 훈련 및 직렬화 유틸리티가 추가되었다. 

In [74]:
from tensorflow.keras import layers


class Sampling(layers.Layer):
    
    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.keras.backend.random_normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

    
class Encoder(layers.Layer):
    
    def __init__(self, latent_dim=32, intermediate_dim=64, name="encoder", **kwargs):
        super(Encoder, self).__init__(name=name, **kwargs)
        self.dense_proj = layers.Dense(intermediate_dim, activation="relu")
        self.dense_mean = layers.Dense(latent_dim)
        self.dense_log_var = layers.Dense(latent_dim)
        self.sampling = Sampling()
    
    def call(self, inputs):
        x = self.dense_proj(inputs)
        z_mean = self.dense_mean(x)
        z_log_var = self.dense_log_var(x)
        z = self.sampling((z_mean, z_log_var))
        return z_mean, z_log_var, z

class Decoder(layers.Layer):
    
    def __init__(self, original_dim, intermediate_dim=64, name="decoder", **kwargs):
        super(Decoder, self).__init__(name=name, **kwargs)
        self.dense_proj = layers.Dense(intermediate_dim, activation="relu")
        self.dense_output = layers.Dense(original_dim, activation="sigmoid")
    
    def call(self, inputs):
        x = self.dense_proj(inputs)
        return self.dense_output(x)

class VariationalAutoEncoder(keras.Model):
    
    def __init__(
        self,
        original_dim,
        intermediate_dim=64,
        latent_dim=32,
        name="autoencoder",
        **kwargs
    ):
        super(VariationalAutoEncoder, self).__init__(name=name, **kwargs)
        self.original_dim = original_dim
        self.encoder = Encoder(latent_dim=latent_dim, intermediate_dim=intermediate_dim)
        self.decoder = Decoder(original_dim, intermediate_dim=intermediate_dim)

    
    def call(self, inputs):
        z_mean, z_log_var, z = self.encoder(inputs)
        reconstructed = self.decoder(z)
        kl_loss = -0.5 * tf.reduce_mean(
            z_log_var - tf.square(z_mean) - tf.exp(z_log_var) + 1
        )
        self.add_loss(kl_loss)
        return reconstructed

In [75]:
# Mnist 훈련셋으로 작성해보자.

original_dim = 784
vae = VariationalAutoEncoder(original_dim, 64, 32)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
mse_loss_fn = tf.keras.losses.MeanSquaredError()

loss_metric = tf.keras.metrics.Mean()

(x_train, _), _ = tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(60000, 784).astype("float32") / 255

train_dataset = tf.data.Dataset.from_tensor_slices(x_train)
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(64)


epochs = 2

# GradientTape : tf 2.0의 자동미분 기능. 자동 미분을 통해 동적으로 Gradient 값들을 확인해 볼 수 있다는 장점. 
for epoch in range(epochs):
    print(f"Start of epoch {epoch}")
    
    for step, x_batch_train in enumerate(train_dataset):
        with tf.GradientTape() as tape:
            reconstructed = vae(x_batch_train)
            print(reconstructed)
            # loss 계산하기
            loss = mse_loss_fn(x_batch_train, reconstructed)
            loss += sum(vae.losses)

        # 자동 미분한 값.
        grads = tape.gradient(loss, vae.trainable_weights)
        
        # 오차 역전파 - weight 업데이트
        optimizer.apply_gradients(zip(grads, vae.trainable_weights))
        
        loss_metric(loss)
        
        if step % 100 == 0:
            print(f"step {step}: mean loss = {loss_metric.result():.4f}")
    

Start of epoch 0
tf.Tensor(
[[0.43198273 0.53926325 0.41804683 ... 0.44642615 0.5071694  0.58154047]
 [0.34491563 0.37025565 0.49377084 ... 0.42748773 0.46966588 0.49509022]
 [0.3812223  0.49734446 0.49654627 ... 0.5069141  0.44490802 0.5271926 ]
 ...
 [0.39885926 0.48308352 0.47132194 ... 0.4332949  0.5211846  0.46213692]
 [0.43373668 0.42846504 0.520784   ... 0.4102093  0.5024845  0.5764835 ]
 [0.51846504 0.49455482 0.5531564  ... 0.40880558 0.4995705  0.60292864]], shape=(64, 784), dtype=float32)
step 0: mean loss = 0.3270
tf.Tensor(
[[0.34548348 0.45542234 0.49778092 ... 0.5453984  0.43787524 0.5355891 ]
 [0.38591364 0.47996294 0.41595474 ... 0.44235212 0.50544745 0.47060737]
 [0.46727324 0.46435145 0.48273945 ... 0.49790028 0.45729205 0.5048195 ]
 ...
 [0.39377487 0.43628132 0.45956165 ... 0.4483252  0.48820668 0.5675961 ]
 [0.3844879  0.49516046 0.43987137 ... 0.4450549  0.52914417 0.5168865 ]
 [0.39200583 0.4078884  0.57771945 ... 0.4309301  0.45331898 0.52905196]], shape=(64, 7

tf.Tensor(
[[0.24793422 0.25509518 0.25025263 ... 0.27093202 0.27773067 0.26303262]
 [0.3189836  0.3871209  0.4153673  ... 0.36646053 0.35583624 0.3576386 ]
 [0.3648281  0.35981315 0.31464744 ... 0.366203   0.34915704 0.37686196]
 ...
 [0.26479203 0.4011957  0.35440475 ... 0.38517871 0.32139304 0.34862378]
 [0.39390266 0.33688363 0.32018864 ... 0.38576886 0.44317287 0.34850746]
 [0.2554896  0.3694689  0.36100435 ... 0.2918399  0.34231514 0.36995828]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.3070829  0.43088382 0.33429584 ... 0.36010057 0.42439142 0.41081965]
 [0.29374778 0.41330716 0.3458702  ... 0.31433475 0.34439117 0.34884477]
 [0.2656741  0.3009115  0.32629538 ... 0.23676053 0.28177965 0.28191644]
 ...
 [0.35556898 0.3684768  0.2836946  ... 0.27609754 0.27616054 0.2525503 ]
 [0.33494043 0.30411068 0.2953337  ... 0.3221689  0.3213727  0.2640192 ]
 [0.21148956 0.40779218 0.32433897 ... 0.28369206 0.23498422 0.33558422]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.2900769  

tf.Tensor(
[[0.1596139  0.23429647 0.23562774 ... 0.163414   0.17531723 0.2549065 ]
 [0.2043662  0.21738487 0.23555055 ... 0.1589545  0.19815254 0.22653854]
 [0.1464087  0.20507646 0.22032437 ... 0.2070649  0.20486411 0.23554492]
 ...
 [0.220079   0.19796547 0.18914047 ... 0.21496978 0.23963419 0.16031656]
 [0.11527416 0.17701557 0.22045442 ... 0.21412304 0.22692391 0.24125946]
 [0.2624337  0.21422511 0.19079298 ... 0.21479893 0.22242686 0.23096368]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.14126131 0.14183712 0.15167326 ... 0.1333777  0.1390078  0.12878042]
 [0.11280769 0.16417676 0.10495213 ... 0.06761393 0.11782306 0.16335359]
 [0.10765615 0.15573108 0.12141576 ... 0.08981866 0.08262235 0.11504149]
 ...
 [0.19072717 0.22678399 0.19836363 ... 0.18889093 0.20612773 0.24982256]
 [0.10155988 0.15290698 0.20751551 ... 0.10908478 0.14274961 0.16090101]
 [0.17888135 0.19522029 0.19428757 ... 0.14328927 0.20752183 0.21588817]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.20993996 

tf.Tensor(
[[0.07412913 0.11139989 0.09327677 ... 0.07533097 0.1277901  0.08446133]
 [0.11810431 0.12763932 0.12796175 ... 0.10158831 0.12784562 0.13656303]
 [0.09723648 0.13551971 0.09021434 ... 0.11522111 0.10229477 0.11208606]
 ...
 [0.04254672 0.08374962 0.07202798 ... 0.07666352 0.09321037 0.1282847 ]
 [0.10229009 0.16918245 0.0975346  ... 0.11502257 0.13807395 0.13571408]
 [0.22476208 0.14906615 0.15388331 ... 0.10631064 0.1339455  0.1884695 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.13528398 0.13346988 0.12405229 ... 0.12595072 0.14962474 0.12055603]
 [0.1711342  0.17135733 0.19998214 ... 0.23029724 0.14693773 0.2070432 ]
 [0.16028756 0.1897487  0.15627494 ... 0.17892858 0.20102313 0.16016048]
 ...
 [0.12429738 0.18095249 0.14762935 ... 0.18014145 0.18550554 0.14713648]
 [0.13893846 0.10593554 0.08808869 ... 0.08565745 0.14967519 0.0957633 ]
 [0.17188668 0.14945    0.12906697 ... 0.13918114 0.17208105 0.13262078]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.13138282 

tf.Tensor(
[[0.09692031 0.10461494 0.1243718  ... 0.10144567 0.11052245 0.12413421]
 [0.1077472  0.12155765 0.15544865 ... 0.12918058 0.14967752 0.14183998]
 [0.07846227 0.12389648 0.08228782 ... 0.10888898 0.11068767 0.1375477 ]
 ...
 [0.10132524 0.14307177 0.09251073 ... 0.14281762 0.12495694 0.11247298]
 [0.08070433 0.09312207 0.08051547 ... 0.07052994 0.07284907 0.14062804]
 [0.13428035 0.09896907 0.12414676 ... 0.10816702 0.11399546 0.12516463]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.04590559 0.11919561 0.1032221  ... 0.10739809 0.06745991 0.11031863]
 [0.03991854 0.06336778 0.06172293 ... 0.05072325 0.04122871 0.05085349]
 [0.15028805 0.07998532 0.06100538 ... 0.09354353 0.09027189 0.06050599]
 ...
 [0.126329   0.14975485 0.12427181 ... 0.14040807 0.1806443  0.20588556]
 [0.07873145 0.13913661 0.15173155 ... 0.14331287 0.11605722 0.14694679]
 [0.22522482 0.21428248 0.17750344 ... 0.15690187 0.18258598 0.1865288 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.1198841  

tf.Tensor(
[[0.07608363 0.11600497 0.1300368  ... 0.11632895 0.08569697 0.10524175]
 [0.07502258 0.11830282 0.10774824 ... 0.09631002 0.06554863 0.11205107]
 [0.08009258 0.09811616 0.08216101 ... 0.10879171 0.09749785 0.09950879]
 ...
 [0.147122   0.10725296 0.07383084 ... 0.09266493 0.15896267 0.12289986]
 [0.04548427 0.06068113 0.03558215 ... 0.04333794 0.09434155 0.06220642]
 [0.07404122 0.05521682 0.05232331 ... 0.04007062 0.04661614 0.07454681]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.07771644 0.07920393 0.12772518 ... 0.11780739 0.10160223 0.12132451]
 [0.06718457 0.05447111 0.08624849 ... 0.04066738 0.05702716 0.09373355]
 [0.16700906 0.1722816  0.148009   ... 0.18637303 0.18302369 0.15554857]
 ...
 [0.10997519 0.14457765 0.08141005 ... 0.08776563 0.09383988 0.10591096]
 [0.06060249 0.05805573 0.05621138 ... 0.03652766 0.06175762 0.08878285]
 [0.03943008 0.06792819 0.06400394 ... 0.07565227 0.07583222 0.07251328]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.04299587 

tf.Tensor(
[[0.09540418 0.08043081 0.09103292 ... 0.08956301 0.09420112 0.11227179]
 [0.14743397 0.11890095 0.09806523 ... 0.10778993 0.14553049 0.1279065 ]
 [0.04489696 0.0794462  0.06319076 ... 0.05914924 0.04608962 0.06254643]
 ...
 [0.06459847 0.09323347 0.08386612 ... 0.0622167  0.07251686 0.08070767]
 [0.04708949 0.06127876 0.07013652 ... 0.09533477 0.08125719 0.08042505]
 [0.04054618 0.02741575 0.02590868 ... 0.02655661 0.03508595 0.02716219]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.06247592 0.0882552  0.0548915  ... 0.08159724 0.0514493  0.08914739]
 [0.03600246 0.04472488 0.03717428 ... 0.06558692 0.04501626 0.04541892]
 [0.15319273 0.19160286 0.1080794  ... 0.08718389 0.12233731 0.14937901]
 ...
 [0.0505257  0.06560025 0.08484283 ... 0.08512837 0.09662804 0.08720985]
 [0.07150877 0.09072539 0.04401901 ... 0.06957927 0.10064229 0.06573606]
 [0.05971056 0.06074941 0.09594026 ... 0.0608198  0.0614731  0.0959844 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03795016 

tf.Tensor(
[[0.06236294 0.05787572 0.05730656 ... 0.05433637 0.08075488 0.12180984]
 [0.04826584 0.05752167 0.06061441 ... 0.06620046 0.04533255 0.08686453]
 [0.05714154 0.09992105 0.06564564 ... 0.06541878 0.07004678 0.06375235]
 ...
 [0.06184804 0.11727899 0.06481719 ... 0.08622319 0.12553799 0.09455881]
 [0.07589105 0.09086007 0.0446015  ... 0.0445908  0.06785128 0.0603666 ]
 [0.09580445 0.09692615 0.15059364 ... 0.11173773 0.13084236 0.11400294]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03735816 0.04248816 0.0495472  ... 0.03438661 0.04787984 0.05976847]
 [0.0962683  0.07986808 0.04852563 ... 0.0493398  0.09159949 0.07545295]
 [0.02903223 0.0239808  0.0220834  ... 0.03353417 0.03377795 0.01987723]
 ...
 [0.0412606  0.07185829 0.09426901 ... 0.05885208 0.10008276 0.06947032]
 [0.03220141 0.03514281 0.04548061 ... 0.03823212 0.02871317 0.03574261]
 [0.09270498 0.05984628 0.06581303 ... 0.05586091 0.08990908 0.11636341]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03628814 

tf.Tensor(
[[0.060148   0.07300857 0.0770877  ... 0.07919738 0.06228983 0.0523707 ]
 [0.02951694 0.03710416 0.04414403 ... 0.03230354 0.04699239 0.04762727]
 [0.07872176 0.11269787 0.07073548 ... 0.05817878 0.07502297 0.08689463]
 ...
 [0.0678001  0.09103516 0.06240654 ... 0.0936853  0.06464171 0.06828886]
 [0.03113154 0.04171115 0.06405804 ... 0.04965222 0.04863644 0.06495884]
 [0.02720377 0.06104693 0.04681733 ... 0.04372534 0.05854404 0.03849176]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02591717 0.04516909 0.059403   ... 0.06445962 0.03867525 0.06274867]
 [0.06136978 0.056086   0.04173276 ... 0.03352597 0.03305188 0.04944128]
 [0.09295267 0.09055722 0.05449098 ... 0.09347275 0.08516124 0.11835098]
 ...
 [0.05651346 0.08931974 0.09810925 ... 0.09942552 0.1055927  0.10319301]
 [0.09174457 0.06148365 0.06728783 ... 0.05660725 0.06103313 0.06591886]
 [0.0377273  0.06355685 0.05910373 ... 0.04024202 0.06163913 0.06680334]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.06318077 

tf.Tensor(
[[0.01831117 0.02535531 0.02138957 ... 0.01784709 0.0243209  0.02702686]
 [0.07018593 0.0663999  0.09702808 ... 0.08983815 0.08047268 0.10566732]
 [0.04723683 0.04722637 0.05614224 ... 0.05306074 0.06659126 0.03118491]
 ...
 [0.02424204 0.02926937 0.02854189 ... 0.04464397 0.0382311  0.03990361]
 [0.06625772 0.06247091 0.07055834 ... 0.07907081 0.07079357 0.06364304]
 [0.02947733 0.03360453 0.04596183 ... 0.01917109 0.04764637 0.03966555]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03619921 0.04195815 0.03502452 ... 0.0362573  0.04774079 0.02712199]
 [0.06676599 0.0515838  0.05061516 ... 0.04269105 0.06192237 0.05308399]
 [0.03335202 0.04101062 0.06044111 ... 0.07434514 0.03573951 0.05304864]
 ...
 [0.04138142 0.07514608 0.05697152 ... 0.08462623 0.05194286 0.06413835]
 [0.03101999 0.03575933 0.0548929  ... 0.0413658  0.03845084 0.0529575 ]
 [0.05862352 0.08170238 0.05009896 ... 0.12851217 0.06527981 0.07830375]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.10514474 

tf.Tensor(
[[0.06791353 0.09102386 0.07030603 ... 0.06616291 0.07465678 0.09227857]
 [0.04859763 0.08452719 0.06022093 ... 0.06826642 0.0455586  0.06790465]
 [0.04275838 0.06687075 0.05306545 ... 0.04209009 0.03743893 0.05240765]
 ...
 [0.02046394 0.04866391 0.03362387 ... 0.04962283 0.02094898 0.03836128]
 [0.03006878 0.04643342 0.03687727 ... 0.04707551 0.03517973 0.03986982]
 [0.03587946 0.02760568 0.02185875 ... 0.02482459 0.0363251  0.03836867]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.07659274 0.11113808 0.07638526 ... 0.07344824 0.06172341 0.07884601]
 [0.03157833 0.04660788 0.03056046 ... 0.03843948 0.02545843 0.04431716]
 [0.07543451 0.09067169 0.08796218 ... 0.09856284 0.10724485 0.05762386]
 ...
 [0.04366663 0.05606693 0.05064705 ... 0.07483086 0.05575052 0.06042498]
 [0.10347468 0.05564073 0.05175483 ... 0.08658373 0.09229553 0.04474753]
 [0.0542146  0.06225392 0.06342155 ... 0.08344027 0.08678293 0.08778936]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.04099166 

tf.Tensor(
[[0.04369256 0.02783293 0.03307205 ... 0.02661332 0.03610525 0.02290276]
 [0.02317229 0.04310572 0.0343186  ... 0.04233584 0.05180943 0.0408105 ]
 [0.02762464 0.0319657  0.04657409 ... 0.03145197 0.04636106 0.02380288]
 ...
 [0.07038248 0.04811049 0.04237834 ... 0.03985712 0.0829947  0.08972678]
 [0.02963367 0.02929103 0.05857268 ... 0.04152146 0.03250149 0.04382393]
 [0.07110831 0.04277802 0.03493315 ... 0.05076307 0.05759278 0.04609737]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01323628 0.0231992  0.02620274 ... 0.02965528 0.01935798 0.02485284]
 [0.06243902 0.04444394 0.04753846 ... 0.06473702 0.07481608 0.0358274 ]
 [0.07583472 0.08666512 0.08357671 ... 0.07333902 0.10231528 0.10223401]
 ...
 [0.04299653 0.07123098 0.06931239 ... 0.04060614 0.04983962 0.03446269]
 [0.08513385 0.06666198 0.09670883 ... 0.07733101 0.09160197 0.080185  ]
 [0.03200597 0.0326148  0.03832591 ... 0.02512515 0.03758261 0.03627712]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.05136988 

tf.Tensor(
[[0.05043638 0.04122707 0.03810036 ... 0.04918417 0.04785085 0.05512354]
 [0.05456877 0.05452904 0.0663231  ... 0.0533289  0.05446818 0.04727083]
 [0.0294365  0.03453711 0.03059438 ... 0.04125068 0.03212935 0.02422354]
 ...
 [0.04975027 0.07455435 0.06430414 ... 0.06270322 0.08310273 0.06636664]
 [0.01435935 0.01811224 0.01405767 ... 0.01982453 0.02587524 0.01278165]
 [0.03185833 0.04942182 0.02666944 ... 0.031142   0.02948335 0.02806601]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02780128 0.0330441  0.04359147 ... 0.02491167 0.02188447 0.03352037]
 [0.03262997 0.02399534 0.01333216 ... 0.02927566 0.01902339 0.02284697]
 [0.02909169 0.01747057 0.01850057 ... 0.01561937 0.02488756 0.02183232]
 ...
 [0.03038776 0.02810219 0.02476224 ... 0.028056   0.04450926 0.01482534]
 [0.02404854 0.04253542 0.04288578 ... 0.0319989  0.05052102 0.03300068]
 [0.02615538 0.02686659 0.03710026 ... 0.02163979 0.03367457 0.032442  ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.04613122 

tf.Tensor(
[[0.03535283 0.02113971 0.01727042 ... 0.0196467  0.03041166 0.03771996]
 [0.02330789 0.02230895 0.01723439 ... 0.01358211 0.03089082 0.02205795]
 [0.05219808 0.10527399 0.07070157 ... 0.09425092 0.0880636  0.07901701]
 ...
 [0.04057589 0.04942659 0.0549975  ... 0.03707066 0.05649075 0.06389827]
 [0.05598477 0.06588334 0.03687617 ... 0.04437318 0.05487427 0.03225288]
 [0.04286665 0.0625194  0.05185294 ... 0.06878468 0.05130279 0.05526409]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03451836 0.04068285 0.02121413 ... 0.01548141 0.04439825 0.02942383]
 [0.01373389 0.01687381 0.03320745 ... 0.02980345 0.02446541 0.02788156]
 [0.01826257 0.02248657 0.01941496 ... 0.02308658 0.02038553 0.04625124]
 ...
 [0.05042559 0.05699679 0.07881531 ... 0.05212468 0.04239726 0.06694466]
 [0.01209563 0.01362941 0.00827566 ... 0.01183677 0.01940796 0.0128431 ]
 [0.02028996 0.03514647 0.044649   ... 0.03844944 0.03588015 0.0336867 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.05126768 

tf.Tensor(
[[0.03444397 0.03974286 0.03964028 ... 0.03082427 0.0338484  0.03021818]
 [0.03477567 0.05062068 0.04790249 ... 0.03602326 0.04145375 0.04146853]
 [0.01769015 0.02633813 0.03044304 ... 0.06440315 0.02061293 0.0442633 ]
 ...
 [0.05372131 0.04230252 0.02472839 ... 0.0123311  0.03210682 0.0404292 ]
 [0.07509094 0.07542226 0.07066202 ... 0.06702489 0.07530412 0.07649812]
 [0.03898627 0.04940477 0.04227218 ... 0.03732276 0.05511934 0.04881266]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.04375264 0.0266307  0.02673587 ... 0.02566165 0.04331014 0.04540974]
 [0.03798023 0.06372166 0.0600186  ... 0.03086084 0.03590211 0.06368399]
 [0.02499324 0.04252094 0.05840093 ... 0.03566107 0.04340881 0.04910451]
 ...
 [0.03081119 0.03551981 0.03196481 ... 0.04199064 0.02331397 0.03683695]
 [0.01140189 0.02665082 0.01654693 ... 0.01061335 0.00609118 0.01344389]
 [0.05019659 0.04896432 0.03245184 ... 0.03371444 0.03778565 0.0407145 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02191749 

tf.Tensor(
[[0.04016271 0.03794968 0.02967089 ... 0.03299594 0.0357734  0.03578854]
 [0.01138476 0.01744756 0.01940989 ... 0.02810878 0.02219832 0.02338862]
 [0.02529925 0.0344699  0.02734452 ... 0.03471458 0.02310079 0.03098628]
 ...
 [0.04518521 0.03978837 0.05422279 ... 0.02645582 0.04315221 0.03898585]
 [0.03140667 0.03575158 0.03293812 ... 0.03454676 0.0430913  0.05281249]
 [0.04856843 0.05336097 0.07749277 ... 0.07209793 0.05135658 0.04511213]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02531472 0.01536456 0.02278179 ... 0.0090211  0.01503885 0.01684174]
 [0.0371975  0.05601382 0.05203813 ... 0.05025232 0.06145468 0.0619601 ]
 [0.01184246 0.01201141 0.01532233 ... 0.00854346 0.015928   0.01180488]
 ...
 [0.01461697 0.02694675 0.01959938 ... 0.02326107 0.0148735  0.02105772]
 [0.02886972 0.03943267 0.0395799  ... 0.03685933 0.03303239 0.0252082 ]
 [0.01646453 0.02546564 0.0280599  ... 0.03150037 0.02876094 0.0308761 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02912354 

tf.Tensor(
[[0.01149878 0.01395592 0.01347321 ... 0.01701689 0.01179105 0.02142903]
 [0.04538262 0.05174536 0.05229789 ... 0.02406535 0.0386402  0.04545555]
 [0.02146372 0.01892227 0.02266848 ... 0.02283645 0.02033937 0.02114749]
 ...
 [0.02367634 0.03916535 0.04301539 ... 0.01438096 0.03574732 0.03228599]
 [0.01233026 0.035319   0.04250064 ... 0.02173567 0.02741584 0.02341074]
 [0.01421729 0.02508497 0.02452302 ... 0.01687098 0.01617542 0.019299  ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.05650911 0.04955617 0.05259535 ... 0.05732846 0.05938941 0.04467258]
 [0.02050093 0.02107936 0.01635122 ... 0.01577547 0.02502662 0.02019921]
 [0.0070504  0.01514456 0.02643055 ... 0.02497014 0.01142895 0.01953426]
 ...
 [0.03942356 0.04944208 0.05195197 ... 0.05940634 0.046947   0.04866111]
 [0.04854032 0.05896318 0.056364   ... 0.0699687  0.06954342 0.06884509]
 [0.0444375  0.0648599  0.03717491 ... 0.06174675 0.03820467 0.05397272]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.05212888 

tf.Tensor(
[[0.02289781 0.03424481 0.03360388 ... 0.02734464 0.02933776 0.03979641]
 [0.01639655 0.01783928 0.01357532 ... 0.01456675 0.017744   0.01398525]
 [0.05047867 0.03494972 0.03222817 ... 0.03325221 0.04032308 0.03717297]
 ...
 [0.02954775 0.02444154 0.01944107 ... 0.01378164 0.01459944 0.04851547]
 [0.01465669 0.01677796 0.01629797 ... 0.01142755 0.02265531 0.01029444]
 [0.01183498 0.01213887 0.02401453 ... 0.01015168 0.01473975 0.0145838 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.05677697 0.03357181 0.02390665 ... 0.02429968 0.03783053 0.03314355]
 [0.03110057 0.0314644  0.04087818 ... 0.02996919 0.04930124 0.0317868 ]
 [0.02425337 0.02835247 0.02465019 ... 0.02477765 0.01743925 0.01785499]
 ...
 [0.01158476 0.01782495 0.00955173 ... 0.01115391 0.00931004 0.01613545]
 [0.03393096 0.03017399 0.02289185 ... 0.02596796 0.03017533 0.03305128]
 [0.02870253 0.02745613 0.01441482 ... 0.02468905 0.02086043 0.01260915]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01519558 

tf.Tensor(
[[0.0155946  0.02844837 0.01818421 ... 0.01830867 0.0203875  0.01487702]
 [0.04013571 0.07212207 0.04607391 ... 0.06627023 0.04122171 0.04522455]
 [0.02865696 0.05548108 0.04464817 ... 0.04659426 0.05635962 0.05116311]
 ...
 [0.09256539 0.05397999 0.03296834 ... 0.06537166 0.05887121 0.06733322]
 [0.02787703 0.04558933 0.02888191 ... 0.01933819 0.0183976  0.02951667]
 [0.0269354  0.02164251 0.02000338 ... 0.01745507 0.02536878 0.02765492]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03640869 0.04346094 0.03191748 ... 0.01997122 0.02450174 0.04506931]
 [0.02311856 0.01660728 0.0226385  ... 0.01893735 0.02585581 0.01885039]
 [0.01596546 0.02403918 0.0257234  ... 0.03350472 0.0326477  0.02857864]
 ...
 [0.01771784 0.01994115 0.02306834 ... 0.01367861 0.01664504 0.02687612]
 [0.06941625 0.04444739 0.01248899 ... 0.02469438 0.02958167 0.01880568]
 [0.03418598 0.02773866 0.02577525 ... 0.03284991 0.03044304 0.03892297]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00784692 

tf.Tensor(
[[0.00888768 0.0090453  0.01111469 ... 0.00891879 0.01380444 0.01240763]
 [0.0491662  0.07449853 0.07536763 ... 0.08007893 0.09248084 0.07611474]
 [0.0180335  0.01803786 0.01570198 ... 0.01069555 0.02180696 0.01893261]
 ...
 [0.02384874 0.03037569 0.01787937 ... 0.02625865 0.03380159 0.02894035]
 [0.03506929 0.02251798 0.02391824 ... 0.03228325 0.02191299 0.01867178]
 [0.0443095  0.04084814 0.02569711 ... 0.0402554  0.031928   0.03296253]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.04034472 0.04699698 0.05638507 ... 0.03334215 0.0391995  0.07617217]
 [0.02145723 0.02921569 0.02589053 ... 0.0296303  0.03161883 0.03952661]
 [0.00721478 0.01024139 0.00842497 ... 0.00730747 0.00931159 0.00537711]
 ...
 [0.00506401 0.00671333 0.0072681  ... 0.01319432 0.00647882 0.01702821]
 [0.01538569 0.02303609 0.02101979 ... 0.01892805 0.01404357 0.02407262]
 [0.02426815 0.02493849 0.02537277 ... 0.01504481 0.02390036 0.02175075]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00614628 

tf.Tensor(
[[0.01327032 0.01658288 0.02607512 ... 0.02047637 0.03025371 0.03599566]
 [0.02269268 0.02059835 0.0341464  ... 0.01599094 0.03745037 0.03036302]
 [0.04983315 0.05076021 0.05508715 ... 0.03305992 0.04934269 0.04477394]
 ...
 [0.02854747 0.04825667 0.04337555 ... 0.03925771 0.03361148 0.03554341]
 [0.05119374 0.0333713  0.05402458 ... 0.05795485 0.04638439 0.06750226]
 [0.00720197 0.0125322  0.01367784 ... 0.00688389 0.0125452  0.01188612]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02875829 0.04352051 0.03076187 ... 0.04641315 0.03013518 0.04888567]
 [0.0105179  0.01200151 0.01915577 ... 0.00699383 0.01068959 0.01827517]
 [0.01422897 0.00791255 0.01103535 ... 0.00834242 0.00900057 0.00876382]
 ...
 [0.0408777  0.04204836 0.03180552 ... 0.03885353 0.03865603 0.06572151]
 [0.0097174  0.02077547 0.01853567 ... 0.01075396 0.01147932 0.02117881]
 [0.02907145 0.03777301 0.04565251 ... 0.05550465 0.03134829 0.05810383]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02763167 

tf.Tensor(
[[0.04325265 0.06031647 0.04328817 ... 0.03965166 0.05427405 0.05021226]
 [0.03164786 0.01958308 0.01398069 ... 0.01942489 0.02511957 0.033043  ]
 [0.02107996 0.02955133 0.02170467 ... 0.0225741  0.01897582 0.01825786]
 ...
 [0.03419882 0.04809564 0.04684535 ... 0.05865139 0.03252268 0.0541355 ]
 [0.00802535 0.01750112 0.01602989 ... 0.01790327 0.02765414 0.01818779]
 [0.03759062 0.04928368 0.05030435 ... 0.04078138 0.03137401 0.05671647]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02260602 0.02254105 0.028465   ... 0.01762283 0.02572146 0.03640398]
 [0.02402756 0.01880005 0.02018139 ... 0.01675463 0.02721867 0.03187191]
 [0.01375082 0.01559716 0.01937234 ... 0.00939557 0.01986524 0.01961032]
 ...
 [0.02045625 0.03609887 0.01867419 ... 0.03105256 0.02941188 0.02687603]
 [0.0227603  0.02141395 0.03649566 ... 0.0216949  0.03149989 0.03769243]
 [0.04622468 0.03867462 0.03654754 ... 0.03820819 0.03788796 0.04456657]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01033041 

tf.Tensor(
[[0.02893221 0.02636749 0.01121297 ... 0.02071834 0.02641186 0.02209893]
 [0.01273653 0.01400256 0.02030745 ... 0.02170458 0.02168199 0.02510935]
 [0.02988327 0.04847416 0.02705383 ... 0.03002718 0.02274036 0.03322199]
 ...
 [0.01552317 0.01404724 0.0172461  ... 0.0153501  0.0172846  0.01912177]
 [0.0433054  0.047313   0.04936373 ... 0.06206495 0.02930421 0.04552177]
 [0.01886967 0.04005766 0.02873981 ... 0.02278656 0.01322001 0.02234995]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01178002 0.01224032 0.00881016 ... 0.00901496 0.00886983 0.01077306]
 [0.0134958  0.02719837 0.03524232 ... 0.04024416 0.01853263 0.03712338]
 [0.04635772 0.06397185 0.04708311 ... 0.03815669 0.03642645 0.03842664]
 ...
 [0.02380523 0.01996118 0.01777446 ... 0.01533189 0.02290601 0.01934287]
 [0.02085048 0.02619445 0.02877983 ... 0.0285565  0.02057022 0.0307737 ]
 [0.03281423 0.03041548 0.02999473 ... 0.03799734 0.02213117 0.02771533]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03698605 

tf.Tensor(
[[0.04534975 0.03230131 0.0291748  ... 0.02295113 0.03430513 0.03789142]
 [0.01112753 0.01421279 0.01092601 ... 0.02167812 0.01062846 0.00786701]
 [0.00692344 0.00683895 0.0072923  ... 0.01408949 0.01244    0.01316428]
 ...
 [0.05273438 0.02944234 0.02236015 ... 0.02798426 0.0294078  0.03447425]
 [0.0369409  0.04752553 0.02608669 ... 0.03133708 0.03951427 0.04461661]
 [0.01031238 0.01403621 0.02050444 ... 0.00763515 0.00800234 0.01146147]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02142084 0.01951396 0.01696882 ... 0.01528403 0.0199841  0.01552394]
 [0.01823246 0.02073431 0.01439345 ... 0.01992652 0.01862699 0.01528025]
 [0.01915088 0.02504468 0.01865658 ... 0.01225433 0.02317306 0.02231058]
 ...
 [0.01248813 0.01166171 0.01996991 ... 0.01710221 0.01411912 0.01514432]
 [0.011834   0.00923622 0.01330024 ... 0.00976187 0.01317802 0.01170853]
 [0.01476139 0.0385159  0.03720292 ... 0.01931271 0.02862668 0.02293459]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00996983 

tf.Tensor(
[[0.02598518 0.02966994 0.03257605 ... 0.04405692 0.02496916 0.02505073]
 [0.00360978 0.00726211 0.01091501 ... 0.01127455 0.01131201 0.00550461]
 [0.03038678 0.03181419 0.03215387 ... 0.02464247 0.02456436 0.04548755]
 ...
 [0.01895303 0.03034461 0.02053937 ... 0.03501129 0.02559337 0.02222973]
 [0.02419576 0.03392506 0.03243279 ... 0.02282873 0.04375333 0.02867013]
 [0.03603849 0.03657281 0.04413131 ... 0.0363442  0.05486467 0.05508855]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00691438 0.00851169 0.01651314 ... 0.00733781 0.00771296 0.01617208]
 [0.04220513 0.0622423  0.03309458 ... 0.03753376 0.02136114 0.03116766]
 [0.01244611 0.02298808 0.01463121 ... 0.01392835 0.02380216 0.01743791]
 ...
 [0.00950706 0.00525904 0.00773305 ... 0.00535038 0.01264235 0.00550482]
 [0.01201668 0.00937477 0.00813606 ... 0.01045319 0.00956172 0.01095447]
 [0.01068512 0.01127508 0.00748956 ... 0.01312155 0.01201531 0.0101766 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00977489 

tf.Tensor(
[[0.00999618 0.00698981 0.01157936 ... 0.0117718  0.00841385 0.01019987]
 [0.01254705 0.01259983 0.01648378 ... 0.01124114 0.01320437 0.01559451]
 [0.00979564 0.01061067 0.01257551 ... 0.0140672  0.00973183 0.00961244]
 ...
 [0.0523802  0.03031585 0.01699916 ... 0.02848655 0.02891961 0.04075199]
 [0.00830564 0.00821653 0.01842985 ... 0.00737727 0.01611608 0.01493225]
 [0.02311116 0.02683014 0.04542047 ... 0.02404022 0.02882466 0.04619819]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01446912 0.01564059 0.0112381  ... 0.02345929 0.01179528 0.01366857]
 [0.02511257 0.04232684 0.0193176  ... 0.0357537  0.03732556 0.02128947]
 [0.03569707 0.04036951 0.02711478 ... 0.04482266 0.04294321 0.0358074 ]
 ...
 [0.01317638 0.02036563 0.02050859 ... 0.01687646 0.01493677 0.01521456]
 [0.02510694 0.02141207 0.02049065 ... 0.02178448 0.02578163 0.02508709]
 [0.0147709  0.00862241 0.01644447 ... 0.02087173 0.01566195 0.01144749]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01999557 

tf.Tensor(
[[0.00626224 0.01279062 0.00747427 ... 0.0056057  0.00717133 0.00466079]
 [0.00789088 0.00983718 0.01154757 ... 0.01891667 0.01719621 0.01230073]
 [0.02058199 0.0176439  0.02061099 ... 0.01523101 0.01410967 0.02250874]
 ...
 [0.02431709 0.06054789 0.04441565 ... 0.03937924 0.03056502 0.03784737]
 [0.01088741 0.01020381 0.01736531 ... 0.01866591 0.01396933 0.0164535 ]
 [0.04494569 0.03790432 0.04084685 ... 0.02217379 0.03238899 0.03716514]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.0149413  0.01716751 0.01860687 ... 0.0163992  0.01957023 0.02570793]
 [0.02287444 0.02183795 0.02825442 ... 0.01411855 0.01786426 0.02918676]
 [0.0110679  0.01586312 0.01677465 ... 0.01412421 0.01595834 0.01015478]
 ...
 [0.0229542  0.02443331 0.02381226 ... 0.02878553 0.02259228 0.02620679]
 [0.02136505 0.03949428 0.02356997 ... 0.05232513 0.03240758 0.03542149]
 [0.0124028  0.02036259 0.03603452 ... 0.01900291 0.0184859  0.02135888]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01526782 

tf.Tensor(
[[0.01516581 0.01616231 0.00825566 ... 0.01054788 0.01537815 0.01105344]
 [0.01493385 0.01419669 0.0055002  ... 0.01305863 0.00694361 0.01103076]
 [0.0083414  0.00400007 0.00477979 ... 0.00567237 0.0059005  0.0055716 ]
 ...
 [0.01040435 0.02299839 0.01529637 ... 0.03315839 0.01588801 0.02027211]
 [0.01948175 0.01778093 0.00955513 ... 0.0260537  0.01657119 0.01518577]
 [0.00743225 0.01048782 0.00917128 ... 0.01087803 0.00703436 0.00970203]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.04984769 0.05524391 0.03220171 ... 0.03373408 0.04915375 0.04839313]
 [0.02557215 0.04268542 0.02275506 ... 0.02845189 0.01888627 0.02625859]
 [0.01454109 0.01237887 0.01258388 ... 0.01459643 0.02363473 0.01520979]
 ...
 [0.02743256 0.02139521 0.02036485 ... 0.01461729 0.02210176 0.02930138]
 [0.01262522 0.01663256 0.01890519 ... 0.01730925 0.01539698 0.02015066]
 [0.00463626 0.00593758 0.00464046 ... 0.00626767 0.00804061 0.00479046]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02862144 

tf.Tensor(
[[0.00758281 0.01126945 0.0090358  ... 0.00587252 0.00606614 0.00860587]
 [0.01462734 0.01244646 0.02301356 ... 0.01400074 0.01243556 0.0202578 ]
 [0.01614609 0.02081031 0.02919042 ... 0.01632443 0.01626211 0.02993697]
 ...
 [0.02021414 0.03259456 0.01779944 ... 0.01357868 0.01839074 0.01610333]
 [0.0113523  0.01127553 0.01590762 ... 0.00943696 0.00979131 0.0210537 ]
 [0.0185155  0.01659629 0.01067549 ... 0.01339179 0.01710311 0.01685202]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01540601 0.01415086 0.02435461 ... 0.01244885 0.01297173 0.02410525]
 [0.00504312 0.00489366 0.00725317 ... 0.00615403 0.01311985 0.01072648]
 [0.02748597 0.03014442 0.04252195 ... 0.02892545 0.03725445 0.04295945]
 ...
 [0.01577771 0.01404303 0.01063758 ... 0.01591545 0.01428318 0.0129301 ]
 [0.02581912 0.02884406 0.02685347 ... 0.0170984  0.02439222 0.04342306]
 [0.01152301 0.01630971 0.00792694 ... 0.01554406 0.01509631 0.01866436]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01129478 

tf.Tensor(
[[0.0114204  0.01601568 0.0101451  ... 0.01700073 0.01971751 0.01204297]
 [0.00993714 0.01446828 0.0164409  ... 0.01257509 0.01163524 0.00897262]
 [0.0312753  0.03704351 0.02536145 ... 0.02398157 0.02993697 0.03314281]
 ...
 [0.01058954 0.00888658 0.00799641 ... 0.0109188  0.01520324 0.02046776]
 [0.01142448 0.00885323 0.01262179 ... 0.00860044 0.01481482 0.01078376]
 [0.02825448 0.02133664 0.01737657 ... 0.02438557 0.01578188 0.01979947]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02333212 0.02458203 0.02302685 ... 0.01178914 0.0312396  0.02222598]
 [0.00869778 0.01121831 0.01639208 ... 0.0233359  0.01158404 0.01531067]
 [0.037662   0.03497326 0.04313549 ... 0.02778548 0.03096661 0.04729885]
 ...
 [0.01227945 0.01441798 0.01220268 ... 0.01545072 0.01688534 0.01549557]
 [0.04480809 0.0427739  0.03899074 ... 0.03207749 0.02661085 0.03885806]
 [0.00841844 0.01088557 0.00649291 ... 0.01229116 0.01225778 0.01238096]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01676691 

tf.Tensor(
[[0.03349972 0.03823936 0.03158018 ... 0.03202429 0.03438637 0.03993192]
 [0.03521022 0.0364601  0.02954656 ... 0.03385508 0.04618302 0.02873507]
 [0.01613563 0.01854035 0.01877642 ... 0.01710483 0.01035821 0.01082176]
 ...
 [0.01886192 0.02714214 0.02748275 ... 0.02413303 0.02943099 0.04152599]
 [0.02245954 0.02004015 0.02362061 ... 0.02365932 0.02534816 0.02905345]
 [0.00211647 0.00628677 0.00424606 ... 0.00477612 0.00732908 0.00326014]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02600077 0.02073771 0.02010569 ... 0.02413762 0.01962209 0.02407148]
 [0.00615573 0.00656578 0.01061767 ... 0.01450005 0.00848576 0.0148668 ]
 [0.00926524 0.01747137 0.01990262 ... 0.01422378 0.02046713 0.02234781]
 ...
 [0.01872    0.02973288 0.03809705 ... 0.03555739 0.02649066 0.03666365]
 [0.00470328 0.00810021 0.00948057 ... 0.00663602 0.00633654 0.00488532]
 [0.01561466 0.01580784 0.01480383 ... 0.01570928 0.0165123  0.01262626]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00562114 

tf.Tensor(
[[0.01464644 0.02497232 0.01568803 ... 0.02601469 0.01015469 0.01863775]
 [0.01525164 0.0263612  0.02111202 ... 0.01834115 0.02914149 0.03044954]
 [0.04285324 0.0462437  0.03259879 ... 0.03428471 0.03967595 0.03292996]
 ...
 [0.01936427 0.02403274 0.04940927 ... 0.02461749 0.02406093 0.03000519]
 [0.03132969 0.03754523 0.03749245 ... 0.04413879 0.0334118  0.03545898]
 [0.01867649 0.01935983 0.01904154 ... 0.02036783 0.01945966 0.0174427 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01230216 0.02849925 0.01546991 ... 0.01466021 0.02718261 0.02468869]
 [0.00555447 0.01016945 0.00988305 ... 0.00542796 0.00497782 0.0068672 ]
 [0.00404766 0.00484133 0.01185346 ... 0.00607514 0.00943327 0.00818923]
 ...
 [0.02106315 0.0239782  0.02179447 ... 0.02654544 0.0339824  0.02402517]
 [0.01399815 0.01554492 0.01536992 ... 0.01225445 0.0192869  0.01046771]
 [0.00949422 0.00941709 0.00454435 ... 0.00979725 0.01458821 0.00777343]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01533625 

tf.Tensor(
[[0.00468257 0.00602907 0.01317745 ... 0.00696245 0.00871745 0.01068363]
 [0.00499979 0.00780851 0.01186657 ... 0.01088318 0.00657439 0.01131871]
 [0.01377648 0.0206283  0.01808983 ... 0.01703736 0.01987642 0.0191704 ]
 ...
 [0.00890481 0.01896    0.0188641  ... 0.03486073 0.01388055 0.03078094]
 [0.00933734 0.00829032 0.02197358 ... 0.01605245 0.01458815 0.01838967]
 [0.02648801 0.01525408 0.01625463 ... 0.01333615 0.01499176 0.01476407]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03579322 0.06522101 0.05081567 ... 0.0629738  0.03952125 0.04835019]
 [0.02409342 0.02198145 0.02428567 ... 0.03283682 0.02758235 0.03094465]
 [0.02133325 0.02500403 0.01635456 ... 0.02006161 0.02950656 0.01677638]
 ...
 [0.0151054  0.02215481 0.03568742 ... 0.01740703 0.01636922 0.03491494]
 [0.0146924  0.02182451 0.01980394 ... 0.01271459 0.01308072 0.0127393 ]
 [0.01352122 0.02217838 0.00776175 ... 0.0158698  0.01355538 0.01044852]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01919547 

tf.Tensor(
[[0.02576458 0.01327664 0.01545104 ... 0.01006278 0.01247248 0.02284282]
 [0.01030701 0.00844213 0.00949693 ... 0.00864482 0.00862372 0.01064131]
 [0.0152939  0.02599952 0.01998034 ... 0.02297288 0.02905154 0.02882767]
 ...
 [0.01770121 0.02134407 0.02106756 ... 0.01904172 0.02688697 0.02490202]
 [0.01728645 0.01272923 0.01232457 ... 0.01527065 0.01386249 0.02062225]
 [0.0076406  0.01383245 0.00945091 ... 0.01203907 0.00683075 0.01259074]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00274289 0.00458226 0.00796071 ... 0.00781399 0.0048424  0.00655091]
 [0.03364581 0.03882584 0.0342471  ... 0.03539869 0.0459047  0.05877292]
 [0.01727563 0.01835924 0.01606917 ... 0.02296793 0.02092421 0.01346087]
 ...
 [0.0368126  0.03132024 0.03704607 ... 0.02789319 0.03765512 0.06864232]
 [0.01174748 0.02108842 0.02337977 ... 0.02759841 0.02258801 0.02172214]
 [0.01120126 0.01542315 0.02555707 ... 0.02072579 0.01873273 0.02254522]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00755957 

tf.Tensor(
[[0.01600099 0.02286348 0.02340299 ... 0.02116647 0.0286603  0.01635712]
 [0.02404198 0.0266237  0.04378435 ... 0.03289279 0.02289087 0.03527987]
 [0.0133101  0.01595113 0.01532701 ... 0.02018052 0.01152849 0.0150789 ]
 ...
 [0.01686916 0.01879451 0.03073478 ... 0.02275208 0.02476004 0.02277741]
 [0.02244556 0.03745872 0.03363428 ... 0.02378449 0.02475616 0.02340552]
 [0.00284442 0.00304756 0.00695232 ... 0.00586677 0.00388342 0.00595045]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.02059463 0.01785323 0.01446706 ... 0.01165584 0.0176875  0.01743102]
 [0.00875321 0.01761523 0.02083504 ... 0.01164377 0.01675239 0.00984547]
 [0.01103315 0.01143235 0.01180649 ... 0.01195827 0.00880927 0.01135167]
 ...
 [0.01232135 0.01905707 0.02205545 ... 0.01540223 0.01853448 0.01883367]
 [0.00859824 0.017391   0.01324251 ... 0.00843653 0.01326954 0.01266822]
 [0.03545484 0.02371436 0.03844872 ... 0.03455845 0.02769011 0.05092338]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.0170275  

tf.Tensor(
[[0.00902569 0.00773033 0.00711057 ... 0.00562412 0.00670445 0.00584447]
 [0.01845786 0.014714   0.01959386 ... 0.01690981 0.01935941 0.01912877]
 [0.0557175  0.04444659 0.03292447 ... 0.03245509 0.03611931 0.04028717]
 ...
 [0.00769705 0.00997621 0.01140028 ... 0.02098051 0.0115532  0.01049456]
 [0.01993296 0.01477137 0.01956087 ... 0.02247658 0.02297729 0.02152234]
 [0.01501566 0.01667243 0.03328565 ... 0.0171403  0.01533672 0.02808654]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00707877 0.01924044 0.01955488 ... 0.01532805 0.01274014 0.01046717]
 [0.04024991 0.03053367 0.03014755 ... 0.05245772 0.03167558 0.03307658]
 [0.01277235 0.02143934 0.02144951 ... 0.01636827 0.02176389 0.01731002]
 ...
 [0.01054615 0.01815376 0.01468098 ... 0.02197948 0.01156828 0.01845682]
 [0.01670873 0.02928218 0.02550086 ... 0.02718312 0.01922736 0.02129489]
 [0.03123108 0.01986706 0.02352449 ... 0.02074665 0.02668628 0.03042164]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.03119737 

tf.Tensor(
[[0.01906955 0.01710841 0.01924261 ... 0.02317542 0.02586421 0.02556741]
 [0.01010957 0.01977098 0.0144839  ... 0.01192868 0.01322144 0.01304299]
 [0.01017252 0.0105294  0.01169443 ... 0.01682356 0.01369005 0.01305857]
 ...
 [0.00827968 0.00903544 0.01776215 ... 0.00754675 0.00752121 0.00844726]
 [0.01890334 0.03863421 0.03373709 ... 0.03731659 0.02508858 0.03008494]
 [0.01118979 0.02533627 0.0162189  ... 0.01867792 0.01625443 0.01251379]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01166365 0.01260266 0.02028498 ... 0.01853293 0.01170632 0.0158217 ]
 [0.02167663 0.01490244 0.02152213 ... 0.01955715 0.01438928 0.02172771]
 [0.00589228 0.00984976 0.01052931 ... 0.00840551 0.00901145 0.00792736]
 ...
 [0.00612384 0.01490432 0.00649619 ... 0.00922251 0.01186422 0.00647351]
 [0.01567358 0.01261282 0.01061308 ... 0.01319629 0.01546788 0.01904139]
 [0.01101309 0.0086565  0.0134986  ... 0.01091239 0.01288015 0.01568592]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01989931 

tf.Tensor(
[[0.00395036 0.00656256 0.00685182 ... 0.00733119 0.00813654 0.00645286]
 [0.00669521 0.00901911 0.00726447 ... 0.00949681 0.00757769 0.00960904]
 [0.00555688 0.00891986 0.01856124 ... 0.01454628 0.01240888 0.01101044]
 ...
 [0.05035612 0.02712128 0.01666594 ... 0.03296438 0.04050529 0.03056306]
 [0.02118668 0.02682376 0.02023619 ... 0.02494028 0.01661834 0.01970384]
 [0.02611828 0.02701083 0.01259163 ... 0.02164307 0.03270912 0.02922687]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01526728 0.01013857 0.01101863 ... 0.00833496 0.00920767 0.01641399]
 [0.00746956 0.00926229 0.01385096 ... 0.00906932 0.00860646 0.01132962]
 [0.02381551 0.02011377 0.0202229  ... 0.01631612 0.0167177  0.02619386]
 ...
 [0.03157008 0.02267411 0.013327   ... 0.01808122 0.0192073  0.02423021]
 [0.01042813 0.02150992 0.0169321  ... 0.0143393  0.01383248 0.01598838]
 [0.00977787 0.0235213  0.01233083 ... 0.02381414 0.00967881 0.01274666]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01855403 

tf.Tensor(
[[0.01210654 0.01118207 0.00851554 ... 0.00370193 0.00975117 0.00882822]
 [0.02949449 0.04134706 0.04912117 ... 0.06446403 0.0476329  0.03730637]
 [0.02506611 0.03565642 0.02735549 ... 0.03141659 0.02390349 0.03306967]
 ...
 [0.03724346 0.02721369 0.01456791 ... 0.02440548 0.03438863 0.01658383]
 [0.02201006 0.02020356 0.01769817 ... 0.01605743 0.03374287 0.01996779]
 [0.01825517 0.02381214 0.01468587 ... 0.02844146 0.01606002 0.02415121]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01403692 0.01539287 0.01193085 ... 0.01578185 0.01448095 0.02696082]
 [0.01177928 0.03127164 0.02265641 ... 0.01690915 0.01551542 0.01222301]
 [0.01455092 0.01164007 0.01375183 ... 0.02792585 0.01608011 0.01261771]
 ...
 [0.01018074 0.01392967 0.01319283 ... 0.00852305 0.01069075 0.01309901]
 [0.00872153 0.0079549  0.01113579 ... 0.00606546 0.00929448 0.01331392]
 [0.01577717 0.01055187 0.00964132 ... 0.00823179 0.00950599 0.01027891]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.0188193  

tf.Tensor(
[[0.00879121 0.01242679 0.01212007 ... 0.01165348 0.01026389 0.00961909]
 [0.01898289 0.01563585 0.02536237 ... 0.0329611  0.01566669 0.0163044 ]
 [0.01858765 0.01497814 0.01465684 ... 0.02131006 0.01381376 0.02289522]
 ...
 [0.01811987 0.02303734 0.00808781 ... 0.01442981 0.01895732 0.01020283]
 [0.0037356  0.00283566 0.00441632 ... 0.00361249 0.00238785 0.00473234]
 [0.02752796 0.02247214 0.02476859 ... 0.02817976 0.02465448 0.03844985]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00466004 0.00429001 0.00720987 ... 0.0083952  0.0053241  0.00476632]
 [0.02375627 0.00994059 0.00513095 ... 0.0107061  0.01725072 0.0084292 ]
 [0.01374295 0.00766101 0.00587875 ... 0.00714394 0.00772849 0.01230857]
 ...
 [0.01183316 0.00982869 0.01535639 ... 0.01883471 0.01685074 0.012445  ]
 [0.00767535 0.00818092 0.01129961 ... 0.00642335 0.01338008 0.00900164]
 [0.0084129  0.00865725 0.01250285 ... 0.01012814 0.00737631 0.0146018 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01615426 

tf.Tensor(
[[0.00984806 0.01499006 0.00759003 ... 0.0220226  0.0101513  0.01082122]
 [0.01116592 0.00774628 0.00881955 ... 0.013044   0.01070952 0.01939452]
 [0.01178354 0.01603317 0.01826441 ... 0.00896177 0.01487276 0.01245695]
 ...
 [0.00920507 0.01105893 0.01250732 ... 0.02018917 0.016783   0.00967604]
 [0.00529632 0.00634316 0.00484541 ... 0.00424117 0.00883791 0.01012468]
 [0.00997591 0.02465767 0.0121347  ... 0.01498529 0.01795951 0.01607326]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00920945 0.00831869 0.00408801 ... 0.00875315 0.00828144 0.00542459]
 [0.00599134 0.00803059 0.00932857 ... 0.0090633  0.00644365 0.00899488]
 [0.01384586 0.01251468 0.01610026 ... 0.01482579 0.01055631 0.01853451]
 ...
 [0.00618312 0.00554043 0.00649232 ... 0.00882894 0.00897896 0.00893927]
 [0.00245902 0.00170928 0.00198421 ... 0.0013907  0.00272509 0.00179765]
 [0.0122492  0.00685436 0.00556636 ... 0.01128575 0.01093557 0.00747693]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01044184 

tf.Tensor(
[[0.01474693 0.02119541 0.00984144 ... 0.01393113 0.01841223 0.02275091]
 [0.0049926  0.00640398 0.00516289 ... 0.00673538 0.00567186 0.00601831]
 [0.00724283 0.01184392 0.01273638 ... 0.01310626 0.00918037 0.00858206]
 ...
 [0.00279868 0.00281325 0.00277022 ... 0.00406575 0.00334674 0.00398076]
 [0.01159814 0.01176625 0.01574552 ... 0.01253912 0.00727069 0.01669866]
 [0.00550395 0.00888899 0.00932389 ... 0.01078233 0.01149076 0.01303345]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00791848 0.00720191 0.01133579 ... 0.00669596 0.00985956 0.00947735]
 [0.00254554 0.00347322 0.00609365 ... 0.00376663 0.00545001 0.00342184]
 [0.01331085 0.00837958 0.01253614 ... 0.01213896 0.01250628 0.00798082]
 ...
 [0.00537249 0.00956324 0.01354337 ... 0.0119659  0.00694066 0.00916782]
 [0.01638967 0.02382764 0.02244493 ... 0.01971704 0.02679405 0.0200817 ]
 [0.01217136 0.01693738 0.01705813 ... 0.01877642 0.01203844 0.01774567]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01328039 

tf.Tensor(
[[0.01400027 0.02276516 0.02498576 ... 0.00958914 0.01767024 0.01892856]
 [0.02570939 0.02014846 0.02051994 ... 0.01764989 0.02980101 0.02227744]
 [0.00746343 0.00820652 0.00988087 ... 0.00633851 0.00913283 0.00888622]
 ...
 [0.00944886 0.00624931 0.01105645 ... 0.01623583 0.01168099 0.01006958]
 [0.01136622 0.01362136 0.01321301 ... 0.01791665 0.00817338 0.00935066]
 [0.01846907 0.01825836 0.02672386 ... 0.01691976 0.0193938  0.0288381 ]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.01669937 0.02603316 0.02022043 ... 0.01736975 0.01825583 0.02324086]
 [0.00872818 0.00922653 0.01126552 ... 0.00912037 0.00920323 0.01259652]
 [0.00399205 0.00276655 0.00288963 ... 0.00290364 0.00380394 0.00405058]
 ...
 [0.02855673 0.01850352 0.01078892 ... 0.0149667  0.01949012 0.01706487]
 [0.01133937 0.00775784 0.0086     ... 0.00371143 0.00791258 0.00740418]
 [0.00449896 0.00742522 0.01165688 ... 0.01208487 0.00895548 0.00941828]], shape=(64, 784), dtype=float32)
tf.Tensor(
[[0.00847319 

KeyboardInterrupt: 

In [65]:
vae = VariationalAutoEncoder(784, 64, 32)

optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)

vae.compile(optimizer, loss=tf.keras.losses.MeanSquaredError())
vae.fit(x_train, x_train, epochs=2, batch_size=64)

Epoch 1/2
938/938 [==============================] - 2s 2ms/step - loss: 0.0748
Epoch 2/2
938/938 [==============================] - 1s 1ms/step - loss: 0.0676
